//-----------------------------------------------------------------------------
//   NOTE: this is a machine generated file - editing not recommended
//
//   File: ./src/com/tshang/peipei/protocol/asn/gogirl/ReqBindPhone.java
//
//   Java class for ASN.1 definition ReqBindPhone as defined in
//   module GOGIRL.
//   This file was generated by Snacc for Java at Tue Jan 26 18:38:18 2016
//-----------------------------------------------------------------------------

package com.tshang.peipei.protocol.asn.gogirl;

// Import PrintStream class for print methods
import java.io.PrintStream;

// Import ASN.1 basic type representations
import com.ibm.util.*;

// Import ASN.1 decoding/encoding classes
import com.ibm.asn1.*;

/** This class represents the ASN.1 SEQUENCE type <tt>ReqBindPhone</tt>.
  * For each sequence member, sequence classes contain a
  * public member variable of the corresponding Java type.
  * @author Snacc for Java
  * @version Tue Jan 26 18:38:16 2016

  */

public class ReqBindPhone implements ASN1Type {

  /** member variable representing the sequence member uid of type java.math.BigInteger */
  public java.math.BigInteger uid;
  /** member variable representing the sequence member phoneno of type byte[] */
  public byte[] phoneno;
  /** member variable representing the sequence member code of type byte[] */
  public byte[] code;
  /** member variable representing the sequence member passwd of type byte[] */
  public byte[] passwd;
  /** member variable representing the sequence member checksum of type byte[] */
  public byte[] checksum;

  /** default constructor */
  public ReqBindPhone() {}

  /** copy constructor */
  public ReqBindPhone (ReqBindPhone arg) {
    uid = arg.uid;
    phoneno = new byte[arg.phoneno.length];
    System.arraycopy(arg.phoneno,0,phoneno,0,arg.phoneno.length);
    code = new byte[arg.code.length];
    System.arraycopy(arg.code,0,code,0,arg.code.length);
    passwd = new byte[arg.passwd.length];
    System.arraycopy(arg.passwd,0,passwd,0,arg.passwd.length);
    checksum = new byte[arg.checksum.length];
    System.arraycopy(arg.checksum,0,checksum,0,arg.checksum.length);
  }

  /** encoding method.
    * @param enc
    *        encoder object derived from com.ibm.asn1.ASN1Encoder
    * @exception com.ibm.asn1.ASN1Exception 
    *            encoding error
    */
  public void encode (ASN1Encoder enc) throws ASN1Exception {
    int seq_nr = enc.encodeSequence();
    enc.encodeInteger(uid);
    enc.encodeOctetString(phoneno);
    enc.encodeOctetString(code);
    enc.encodeOctetString(passwd);
    enc.encodeOctetString(checksum);
    enc.endOf(seq_nr);
  }

  /** decoding method.
    * @param dec
    *        decoder object derived from com.ibm.asn1.ASN1Decoder
    * @exception com.ibm.asn1.ASN1Exception 
    *            decoding error
    */
  public void decode (ASN1Decoder dec) throws ASN1Exception {
    int seq_nr = dec.decodeSequence();
    uid = dec.decodeInteger();
    phoneno = dec.decodeOctetString();
    code = dec.decodeOctetString();
    passwd = dec.decodeOctetString();
    checksum = dec.decodeOctetString();
    dec.endOf(seq_nr);
  }

  /** print method (variable indentation)
    * @param os
    *        PrintStream representing the print destination (file, etc)
    * @param indent
    *        number of blanks that preceed each output line.
    */
  public void print (PrintStream os, int indent) {
    os.println("{ -- SEQUENCE --");
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("uid = ");
    os.print(uid.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("phoneno = ");
    os.print(Hex.toString(phoneno));
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("code = ");
    os.print(Hex.toString(code));
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("passwd = ");
    os.print(Hex.toString(passwd));
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("checksum = ");
    os.print(Hex.toString(checksum));
    os.println();
    for(int ii = 0; ii < indent; ii++) os.print(' ');
    os.print('}');
  }

  /** default print method (fixed indentation)
    * @param os
    *        PrintStream representing the print destination (file, etc)
    */
  public void print (PrintStream os) {
    print(os,0);
  }

  /** toString method
    * @return the output of {@link #print(PrintStream) print} method (fixed indentation) as a string
    */
  public String toString () {
    java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
    PrintStream ps = new PrintStream(baos);
    print(ps);
    ps.close();
    return baos.toString();
  }

}
