//-----------------------------------------------------------------------------
//   NOTE: this is a machine generated file - editing not recommended
//
//   File: ./src/com/tshang/peipei/protocol/asn/gogirl/ReqNotifyAppleIapResult.java
//
//   Java class for ASN.1 definition ReqNotifyAppleIapResult as defined in
//   module GOGIRL.
//   This file was generated by Snacc for Java at Tue Jan 26 18:38:17 2016
//-----------------------------------------------------------------------------

package com.tshang.peipei.protocol.asn.gogirl;

// Import PrintStream class for print methods
import java.io.PrintStream;

// Import ASN.1 basic type representations
import com.ibm.util.*;

// Import ASN.1 decoding/encoding classes
import com.ibm.asn1.*;

/** This class represents the ASN.1 SEQUENCE type <tt>ReqNotifyAppleIapResult</tt>.
  * For each sequence member, sequence classes contain a
  * public member variable of the corresponding Java type.
  * @author Snacc for Java
  * @version Tue Jan 26 18:38:16 2016

  */

public class ReqNotifyAppleIapResult implements ASN1Type {

  /** member variable representing the sequence member uid of type java.math.BigInteger */
  public java.math.BigInteger uid;
  /** member variable representing the sequence member status of type java.math.BigInteger */
  public java.math.BigInteger status;
  /** member variable representing the sequence member transactionid of type byte[] */
  public byte[] transactionid;
  /** member variable representing the sequence member urlencodereceipt of type byte[] */
  public byte[] urlencodereceipt;
  /** member variable representing the sequence member productid of type byte[] */
  public byte[] productid;
  /** member variable representing the sequence member quantity of type java.math.BigInteger */
  public java.math.BigInteger quantity;

  /** default constructor */
  public ReqNotifyAppleIapResult() {}

  /** copy constructor */
  public ReqNotifyAppleIapResult (ReqNotifyAppleIapResult arg) {
    uid = arg.uid;
    status = arg.status;
    transactionid = new byte[arg.transactionid.length];
    System.arraycopy(arg.transactionid,0,transactionid,0,arg.transactionid.length);
    urlencodereceipt = new byte[arg.urlencodereceipt.length];
    System.arraycopy(arg.urlencodereceipt,0,urlencodereceipt,0,arg.urlencodereceipt.length);
    productid = new byte[arg.productid.length];
    System.arraycopy(arg.productid,0,productid,0,arg.productid.length);
    quantity = arg.quantity;
  }

  /** encoding method.
    * @param enc
    *        encoder object derived from com.ibm.asn1.ASN1Encoder
    * @exception com.ibm.asn1.ASN1Exception 
    *            encoding error
    */
  public void encode (ASN1Encoder enc) throws ASN1Exception {
    int seq_nr = enc.encodeSequence();
    enc.encodeInteger(uid);
    enc.encodeInteger(status);
    enc.encodeOctetString(transactionid);
    enc.encodeOctetString(urlencodereceipt);
    enc.encodeOctetString(productid);
    enc.encodeInteger(quantity);
    enc.endOf(seq_nr);
  }

  /** decoding method.
    * @param dec
    *        decoder object derived from com.ibm.asn1.ASN1Decoder
    * @exception com.ibm.asn1.ASN1Exception 
    *            decoding error
    */
  public void decode (ASN1Decoder dec) throws ASN1Exception {
    int seq_nr = dec.decodeSequence();
    uid = dec.decodeInteger();
    status = dec.decodeInteger();
    transactionid = dec.decodeOctetString();
    urlencodereceipt = dec.decodeOctetString();
    productid = dec.decodeOctetString();
    quantity = dec.decodeInteger();
    dec.endOf(seq_nr);
  }

  /** print method (variable indentation)
    * @param os
    *        PrintStream representing the print destination (file, etc)
    * @param indent
    *        number of blanks that preceed each output line.
    */
  public void print (PrintStream os, int indent) {
    os.println("{ -- SEQUENCE --");
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("uid = ");
    os.print(uid.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("status = ");
    os.print(status.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("transactionid = ");
    os.print(Hex.toString(transactionid));
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("urlencodereceipt = ");
    os.print(Hex.toString(urlencodereceipt));
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("productid = ");
    os.print(Hex.toString(productid));
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("quantity = ");
    os.print(quantity.toString());
    os.println();
    for(int ii = 0; ii < indent; ii++) os.print(' ');
    os.print('}');
  }

  /** default print method (fixed indentation)
    * @param os
    *        PrintStream representing the print destination (file, etc)
    */
  public void print (PrintStream os) {
    print(os,0);
  }

  /** toString method
    * @return the output of {@link #print(PrintStream) print} method (fixed indentation) as a string
    */
  public String toString () {
    java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
    PrintStream ps = new PrintStream(baos);
    print(ps);
    ps.close();
    return baos.toString();
  }

}
