//-----------------------------------------------------------------------------
//   NOTE: this is a machine generated file - editing not recommended
//
//   File: ./src/com/tshang/peipei/protocol/asn/gogirl/ReqPublicationDynamics.java
//
//   Java class for ASN.1 definition ReqPublicationDynamics as defined in
//   module GOGIRL.
//   This file was generated by Snacc for Java at Tue Jan 26 18:38:19 2016
//-----------------------------------------------------------------------------

package com.tshang.peipei.protocol.asn.gogirl;

// Import PrintStream class for print methods
import java.io.PrintStream;

// Import ASN.1 basic type representations
import com.ibm.util.*;

// Import ASN.1 decoding/encoding classes
import com.ibm.asn1.*;

/** This class represents the ASN.1 SEQUENCE type <tt>ReqPublicationDynamics</tt>.
  * For each sequence member, sequence classes contain a
  * public member variable of the corresponding Java type.
  * @author Snacc for Java
  * @version Tue Jan 26 18:38:16 2016

  */

public class ReqPublicationDynamics implements ASN1Type {

  /** member variable representing the sequence member uid of type java.math.BigInteger */
  public java.math.BigInteger uid;
  /** member variable representing the sequence member relativetopic of type java.math.BigInteger */
  public java.math.BigInteger relativetopic;
  /** member variable representing the sequence member province of type byte[] */
  public byte[] province;
  /** member variable representing the sequence member city of type byte[] */
  public byte[] city;
  /** member variable representing the sequence member isanonymous of type java.math.BigInteger */
  public java.math.BigInteger isanonymous;
  /** member variable representing the sequence member fonttype of type java.math.BigInteger */
  public java.math.BigInteger fonttype;
  /** member variable representing the sequence member srcpic of type java.math.BigInteger */
  public java.math.BigInteger srcpic;
  /** member variable representing the sequence member topiccontentlist of type GoGirlDataInfoList */
  public GoGirlDataInfoList topiccontentlist = new GoGirlDataInfoList();

  /** default constructor */
  public ReqPublicationDynamics() {}

  /** copy constructor */
  public ReqPublicationDynamics (ReqPublicationDynamics arg) {
    uid = arg.uid;
    relativetopic = arg.relativetopic;
    province = new byte[arg.province.length];
    System.arraycopy(arg.province,0,province,0,arg.province.length);
    city = new byte[arg.city.length];
    System.arraycopy(arg.city,0,city,0,arg.city.length);
    isanonymous = arg.isanonymous;
    fonttype = arg.fonttype;
    srcpic = arg.srcpic;
    topiccontentlist = new GoGirlDataInfoList(arg.topiccontentlist);
  }

  /** encoding method.
    * @param enc
    *        encoder object derived from com.ibm.asn1.ASN1Encoder
    * @exception com.ibm.asn1.ASN1Exception 
    *            encoding error
    */
  public void encode (ASN1Encoder enc) throws ASN1Exception {
    int seq_nr = enc.encodeSequence();
    enc.encodeInteger(uid);
    enc.encodeInteger(relativetopic);
    enc.encodeOctetString(province);
    enc.encodeOctetString(city);
    enc.encodeInteger(isanonymous);
    enc.encodeInteger(fonttype);
    enc.encodeInteger(srcpic);
    topiccontentlist.encode(enc);
    enc.endOf(seq_nr);
  }

  /** decoding method.
    * @param dec
    *        decoder object derived from com.ibm.asn1.ASN1Decoder
    * @exception com.ibm.asn1.ASN1Exception 
    *            decoding error
    */
  public void decode (ASN1Decoder dec) throws ASN1Exception {
    int seq_nr = dec.decodeSequence();
    uid = dec.decodeInteger();
    relativetopic = dec.decodeInteger();
    province = dec.decodeOctetString();
    city = dec.decodeOctetString();
    isanonymous = dec.decodeInteger();
    fonttype = dec.decodeInteger();
    srcpic = dec.decodeInteger();
    topiccontentlist.decode(dec);
    dec.endOf(seq_nr);
  }

  /** print method (variable indentation)
    * @param os
    *        PrintStream representing the print destination (file, etc)
    * @param indent
    *        number of blanks that preceed each output line.
    */
  public void print (PrintStream os, int indent) {
    os.println("{ -- SEQUENCE --");
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("uid = ");
    os.print(uid.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("relativetopic = ");
    os.print(relativetopic.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("province = ");
    os.print(Hex.toString(province));
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("city = ");
    os.print(Hex.toString(city));
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("isanonymous = ");
    os.print(isanonymous.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("fonttype = ");
    os.print(fonttype.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("srcpic = ");
    os.print(srcpic.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("topiccontentlist = ");
    topiccontentlist.print(os, indent+2);
    os.println();
    for(int ii = 0; ii < indent; ii++) os.print(' ');
    os.print('}');
  }

  /** default print method (fixed indentation)
    * @param os
    *        PrintStream representing the print destination (file, etc)
    */
  public void print (PrintStream os) {
    print(os,0);
  }

  /** toString method
    * @return the output of {@link #print(PrintStream) print} method (fixed indentation) as a string
    */
  public String toString () {
    java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
    PrintStream ps = new PrintStream(baos);
    print(ps);
    ps.close();
    return baos.toString();
  }

}
