//-----------------------------------------------------------------------------
//   NOTE: this is a machine generated file - editing not recommended
//
//   File: ./src/com/tshang/peipei/protocol/asn/gogirl/ReqSendBroadcastVoice.java
//
//   Java class for ASN.1 definition ReqSendBroadcastVoice as defined in
//   module GOGIRL.
//   This file was generated by Snacc for Java at Tue Jan 26 18:38:18 2016
//-----------------------------------------------------------------------------

package com.tshang.peipei.protocol.asn.gogirl;

// Import PrintStream class for print methods
import java.io.PrintStream;

// Import ASN.1 basic type representations
import com.ibm.util.*;

// Import ASN.1 decoding/encoding classes
import com.ibm.asn1.*;

/** This class represents the ASN.1 SEQUENCE type <tt>ReqSendBroadcastVoice</tt>.
  * For each sequence member, sequence classes contain a
  * public member variable of the corresponding Java type.
  * @author Snacc for Java
  * @version Tue Jan 26 18:38:16 2016

  */

public class ReqSendBroadcastVoice implements ASN1Type {

  /** member variable representing the sequence member uid of type java.math.BigInteger */
  public java.math.BigInteger uid;
  /** member variable representing the sequence member touids of type GoGirlIntList */
  public GoGirlIntList touids = new GoGirlIntList();
  /** member variable representing the sequence member broadcasttype of type java.math.BigInteger */
  public java.math.BigInteger broadcasttype;
  /** member variable representing the sequence member voicedata of type byte[] */
  public byte[] voicedata;
  /** member variable representing the sequence member voicelen of type java.math.BigInteger */
  public java.math.BigInteger voicelen;

  /** default constructor */
  public ReqSendBroadcastVoice() {}

  /** copy constructor */
  public ReqSendBroadcastVoice (ReqSendBroadcastVoice arg) {
    uid = arg.uid;
    touids = new GoGirlIntList(arg.touids);
    broadcasttype = arg.broadcasttype;
    voicedata = new byte[arg.voicedata.length];
    System.arraycopy(arg.voicedata,0,voicedata,0,arg.voicedata.length);
    voicelen = arg.voicelen;
  }

  /** encoding method.
    * @param enc
    *        encoder object derived from com.ibm.asn1.ASN1Encoder
    * @exception com.ibm.asn1.ASN1Exception 
    *            encoding error
    */
  public void encode (ASN1Encoder enc) throws ASN1Exception {
    int seq_nr = enc.encodeSequence();
    enc.encodeInteger(uid);
    touids.encode(enc);
    enc.encodeInteger(broadcasttype);
    enc.encodeOctetString(voicedata);
    enc.encodeInteger(voicelen);
    enc.endOf(seq_nr);
  }

  /** decoding method.
    * @param dec
    *        decoder object derived from com.ibm.asn1.ASN1Decoder
    * @exception com.ibm.asn1.ASN1Exception 
    *            decoding error
    */
  public void decode (ASN1Decoder dec) throws ASN1Exception {
    int seq_nr = dec.decodeSequence();
    uid = dec.decodeInteger();
    touids.decode(dec);
    broadcasttype = dec.decodeInteger();
    voicedata = dec.decodeOctetString();
    voicelen = dec.decodeInteger();
    dec.endOf(seq_nr);
  }

  /** print method (variable indentation)
    * @param os
    *        PrintStream representing the print destination (file, etc)
    * @param indent
    *        number of blanks that preceed each output line.
    */
  public void print (PrintStream os, int indent) {
    os.println("{ -- SEQUENCE --");
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("uid = ");
    os.print(uid.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("touids = ");
    touids.print(os, indent+2);
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("broadcasttype = ");
    os.print(broadcasttype.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("voicedata = ");
    os.print(Hex.toString(voicedata));
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("voicelen = ");
    os.print(voicelen.toString());
    os.println();
    for(int ii = 0; ii < indent; ii++) os.print(' ');
    os.print('}');
  }

  /** default print method (fixed indentation)
    * @param os
    *        PrintStream representing the print destination (file, etc)
    */
  public void print (PrintStream os) {
    print(os,0);
  }

  /** toString method
    * @return the output of {@link #print(PrintStream) print} method (fixed indentation) as a string
    */
  public String toString () {
    java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
    PrintStream ps = new PrintStream(baos);
    print(ps);
    ps.close();
    return baos.toString();
  }

}
