//-----------------------------------------------------------------------------
//   NOTE: this is a machine generated file - editing not recommended
//
//   File: ./src/com/tshang/peipei/protocol/asn/gogirl/ReqUploadAlbumPic.java
//
//   Java class for ASN.1 definition ReqUploadAlbumPic as defined in
//   module GOGIRL.
//   This file was generated by Snacc for Java at Tue Jan 26 18:38:16 2016
//-----------------------------------------------------------------------------

package com.tshang.peipei.protocol.asn.gogirl;

// Import PrintStream class for print methods
import java.io.PrintStream;

// Import ASN.1 basic type representations
import com.ibm.util.*;

// Import ASN.1 decoding/encoding classes
import com.ibm.asn1.*;

/** This class represents the ASN.1 SEQUENCE type <tt>ReqUploadAlbumPic</tt>.
  * For each sequence member, sequence classes contain a
  * public member variable of the corresponding Java type.
  * @author Snacc for Java
  * @version Tue Jan 26 18:38:16 2016

  */

public class ReqUploadAlbumPic implements ASN1Type {

  /** member variable representing the sequence member uid of type java.math.BigInteger */
  public java.math.BigInteger uid;
  /** member variable representing the sequence member albumid of type java.math.BigInteger */
  public java.math.BigInteger albumid;
  /** member variable representing the sequence member pic of type byte[] */
  public byte[] pic;
  /** member variable representing the sequence member pictitle of type byte[] */
  public byte[] pictitle;
  /** member variable representing the sequence member picdesc of type byte[] */
  public byte[] picdesc;
  /** member variable representing the sequence member islastone of type java.math.BigInteger */
  public java.math.BigInteger islastone;

  /** default constructor */
  public ReqUploadAlbumPic() {}

  /** copy constructor */
  public ReqUploadAlbumPic (ReqUploadAlbumPic arg) {
    uid = arg.uid;
    albumid = arg.albumid;
    pic = new byte[arg.pic.length];
    System.arraycopy(arg.pic,0,pic,0,arg.pic.length);
    pictitle = new byte[arg.pictitle.length];
    System.arraycopy(arg.pictitle,0,pictitle,0,arg.pictitle.length);
    picdesc = new byte[arg.picdesc.length];
    System.arraycopy(arg.picdesc,0,picdesc,0,arg.picdesc.length);
    islastone = arg.islastone;
  }

  /** encoding method.
    * @param enc
    *        encoder object derived from com.ibm.asn1.ASN1Encoder
    * @exception com.ibm.asn1.ASN1Exception 
    *            encoding error
    */
  public void encode (ASN1Encoder enc) throws ASN1Exception {
    int seq_nr = enc.encodeSequence();
    enc.encodeInteger(uid);
    enc.encodeInteger(albumid);
    enc.encodeOctetString(pic);
    enc.encodeOctetString(pictitle);
    enc.encodeOctetString(picdesc);
    enc.encodeInteger(islastone);
    enc.endOf(seq_nr);
  }

  /** decoding method.
    * @param dec
    *        decoder object derived from com.ibm.asn1.ASN1Decoder
    * @exception com.ibm.asn1.ASN1Exception 
    *            decoding error
    */
  public void decode (ASN1Decoder dec) throws ASN1Exception {
    int seq_nr = dec.decodeSequence();
    uid = dec.decodeInteger();
    albumid = dec.decodeInteger();
    pic = dec.decodeOctetString();
    pictitle = dec.decodeOctetString();
    picdesc = dec.decodeOctetString();
    islastone = dec.decodeInteger();
    dec.endOf(seq_nr);
  }

  /** print method (variable indentation)
    * @param os
    *        PrintStream representing the print destination (file, etc)
    * @param indent
    *        number of blanks that preceed each output line.
    */
  public void print (PrintStream os, int indent) {
    os.println("{ -- SEQUENCE --");
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("uid = ");
    os.print(uid.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("albumid = ");
    os.print(albumid.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("pic = ");
    os.print(Hex.toString(pic));
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("pictitle = ");
    os.print(Hex.toString(pictitle));
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("picdesc = ");
    os.print(Hex.toString(picdesc));
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("islastone = ");
    os.print(islastone.toString());
    os.println();
    for(int ii = 0; ii < indent; ii++) os.print(' ');
    os.print('}');
  }

  /** default print method (fixed indentation)
    * @param os
    *        PrintStream representing the print destination (file, etc)
    */
  public void print (PrintStream os) {
    print(os,0);
  }

  /** toString method
    * @return the output of {@link #print(PrintStream) print} method (fixed indentation) as a string
    */
  public String toString () {
    java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
    PrintStream ps = new PrintStream(baos);
    print(ps);
    ps.close();
    return baos.toString();
  }

}
