//-----------------------------------------------------------------------------
//   NOTE: this is a machine generated file - editing not recommended
//
//   File: ./src/com/tshang/peipei/protocol/asn/gogirl/ReqUpdateUserProperty.java
//
//   Java class for ASN.1 definition ReqUpdateUserProperty as defined in
//   module GOGIRL.
//   This file was generated by Snacc for Java at Tue Jan 26 18:38:17 2016
//-----------------------------------------------------------------------------

package com.tshang.peipei.protocol.asn.gogirl;

// Import PrintStream class for print methods
import java.io.PrintStream;

// Import ASN.1 basic type representations
import com.ibm.util.*;

// Import ASN.1 decoding/encoding classes
import com.ibm.asn1.*;

/** This class represents the ASN.1 SEQUENCE type <tt>ReqUpdateUserProperty</tt>.
  * For each sequence member, sequence classes contain a
  * public member variable of the corresponding Java type.
  * @author Snacc for Java
  * @version Tue Jan 26 18:38:16 2016

  */

public class ReqUpdateUserProperty implements ASN1Type {

  /** member variable representing the sequence member uid of type java.math.BigInteger */
  public java.math.BigInteger uid;
  /** member variable representing the sequence member scoreinc of type java.math.BigInteger */
  public java.math.BigInteger scoreinc;
  /** member variable representing the sequence member charminc of type java.math.BigInteger */
  public java.math.BigInteger charminc;
  /** member variable representing the sequence member goldcoininc of type java.math.BigInteger */
  public java.math.BigInteger goldcoininc;
  /** member variable representing the sequence member silvercoininc of type java.math.BigInteger */
  public java.math.BigInteger silvercoininc;
  /** member variable representing the sequence member act of type java.math.BigInteger */
  public java.math.BigInteger act;

  /** default constructor */
  public ReqUpdateUserProperty() {}

  /** copy constructor */
  public ReqUpdateUserProperty (ReqUpdateUserProperty arg) {
    uid = arg.uid;
    scoreinc = arg.scoreinc;
    charminc = arg.charminc;
    goldcoininc = arg.goldcoininc;
    silvercoininc = arg.silvercoininc;
    act = arg.act;
  }

  /** encoding method.
    * @param enc
    *        encoder object derived from com.ibm.asn1.ASN1Encoder
    * @exception com.ibm.asn1.ASN1Exception 
    *            encoding error
    */
  public void encode (ASN1Encoder enc) throws ASN1Exception {
    int seq_nr = enc.encodeSequence();
    enc.encodeInteger(uid);
    enc.encodeInteger(scoreinc);
    enc.encodeInteger(charminc);
    enc.encodeInteger(goldcoininc);
    enc.encodeInteger(silvercoininc);
    enc.encodeInteger(act);
    enc.endOf(seq_nr);
  }

  /** decoding method.
    * @param dec
    *        decoder object derived from com.ibm.asn1.ASN1Decoder
    * @exception com.ibm.asn1.ASN1Exception 
    *            decoding error
    */
  public void decode (ASN1Decoder dec) throws ASN1Exception {
    int seq_nr = dec.decodeSequence();
    uid = dec.decodeInteger();
    scoreinc = dec.decodeInteger();
    charminc = dec.decodeInteger();
    goldcoininc = dec.decodeInteger();
    silvercoininc = dec.decodeInteger();
    act = dec.decodeInteger();
    dec.endOf(seq_nr);
  }

  /** print method (variable indentation)
    * @param os
    *        PrintStream representing the print destination (file, etc)
    * @param indent
    *        number of blanks that preceed each output line.
    */
  public void print (PrintStream os, int indent) {
    os.println("{ -- SEQUENCE --");
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("uid = ");
    os.print(uid.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("scoreinc = ");
    os.print(scoreinc.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("charminc = ");
    os.print(charminc.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("goldcoininc = ");
    os.print(goldcoininc.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("silvercoininc = ");
    os.print(silvercoininc.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("act = ");
    os.print(act.toString());
    os.println();
    for(int ii = 0; ii < indent; ii++) os.print(' ');
    os.print('}');
  }

  /** default print method (fixed indentation)
    * @param os
    *        PrintStream representing the print destination (file, etc)
    */
  public void print (PrintStream os) {
    print(os,0);
  }

  /** toString method
    * @return the output of {@link #print(PrintStream) print} method (fixed indentation) as a string
    */
  public String toString () {
    java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
    PrintStream ps = new PrintStream(baos);
    print(ps);
    ps.close();
    return baos.toString();
  }

}
