//-----------------------------------------------------------------------------
//   NOTE: this is a machine generated file - editing not recommended
//
//   File: ./src/com/tshang/peipei/protocol/asn/gogirl/ReqUpdateRelationship.java
//
//   Java class for ASN.1 definition ReqUpdateRelationship as defined in
//   module GOGIRL.
//   This file was generated by Snacc for Java at Tue Jan 26 18:38:17 2016
//-----------------------------------------------------------------------------

package com.tshang.peipei.protocol.asn.gogirl;

// Import PrintStream class for print methods
import java.io.PrintStream;

// Import ASN.1 basic type representations
import com.ibm.util.*;

// Import ASN.1 decoding/encoding classes
import com.ibm.asn1.*;

/** This class represents the ASN.1 SEQUENCE type <tt>ReqUpdateRelationship</tt>.
  * For each sequence member, sequence classes contain a
  * public member variable of the corresponding Java type.
  * @author Snacc for Java
  * @version Tue Jan 26 18:38:16 2016

  */

public class ReqUpdateRelationship implements ASN1Type {

  /** member variable representing the sequence member uid1 of type java.math.BigInteger */
  public java.math.BigInteger uid1;
  /** member variable representing the sequence member uid2 of type java.math.BigInteger */
  public java.math.BigInteger uid2;
  /** member variable representing the sequence member loyaltyinc of type java.math.BigInteger */
  public java.math.BigInteger loyaltyinc;
  /** member variable representing the sequence member isfocus of type java.math.BigInteger */
  public java.math.BigInteger isfocus;
  /** member variable representing the sequence member giftdeal of type GiftDealInfo */
  public GiftDealInfo giftdeal = new GiftDealInfo();
  /** member variable representing the sequence member focuseduid of type java.math.BigInteger */
  public java.math.BigInteger focuseduid;

  /** default constructor */
  public ReqUpdateRelationship() {}

  /** copy constructor */
  public ReqUpdateRelationship (ReqUpdateRelationship arg) {
    uid1 = arg.uid1;
    uid2 = arg.uid2;
    loyaltyinc = arg.loyaltyinc;
    isfocus = arg.isfocus;
    giftdeal = new GiftDealInfo(arg.giftdeal);
    focuseduid = arg.focuseduid;
  }

  /** encoding method.
    * @param enc
    *        encoder object derived from com.ibm.asn1.ASN1Encoder
    * @exception com.ibm.asn1.ASN1Exception 
    *            encoding error
    */
  public void encode (ASN1Encoder enc) throws ASN1Exception {
    int seq_nr = enc.encodeSequence();
    enc.encodeInteger(uid1);
    enc.encodeInteger(uid2);
    enc.encodeInteger(loyaltyinc);
    enc.encodeInteger(isfocus);
    giftdeal.encode(enc);
    enc.encodeInteger(focuseduid);
    enc.endOf(seq_nr);
  }

  /** decoding method.
    * @param dec
    *        decoder object derived from com.ibm.asn1.ASN1Decoder
    * @exception com.ibm.asn1.ASN1Exception 
    *            decoding error
    */
  public void decode (ASN1Decoder dec) throws ASN1Exception {
    int seq_nr = dec.decodeSequence();
    uid1 = dec.decodeInteger();
    uid2 = dec.decodeInteger();
    loyaltyinc = dec.decodeInteger();
    isfocus = dec.decodeInteger();
    giftdeal.decode(dec);
    focuseduid = dec.decodeInteger();
    dec.endOf(seq_nr);
  }

  /** print method (variable indentation)
    * @param os
    *        PrintStream representing the print destination (file, etc)
    * @param indent
    *        number of blanks that preceed each output line.
    */
  public void print (PrintStream os, int indent) {
    os.println("{ -- SEQUENCE --");
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("uid1 = ");
    os.print(uid1.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("uid2 = ");
    os.print(uid2.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("loyaltyinc = ");
    os.print(loyaltyinc.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("isfocus = ");
    os.print(isfocus.toString());
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("giftdeal = ");
    giftdeal.print(os, indent+2);
    os.println(',');
    for(int ii = 0; ii < indent+2; ii++) os.print(' ');
    os.print("focuseduid = ");
    os.print(focuseduid.toString());
    os.println();
    for(int ii = 0; ii < indent; ii++) os.print(' ');
    os.print('}');
  }

  /** default print method (fixed indentation)
    * @param os
    *        PrintStream representing the print destination (file, etc)
    */
  public void print (PrintStream os) {
    print(os,0);
  }

  /** toString method
    * @return the output of {@link #print(PrintStream) print} method (fixed indentation) as a string
    */
  public String toString () {
    java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
    PrintStream ps = new PrintStream(baos);
    print(ps);
    ps.close();
    return baos.toString();
  }

}
